displayName=NPC stack reorderer
author=Skretzo
support=
description=Reorders NPC stacks with invisible NPCs from showing the oldest NPCs to instead show the newest NPCs
tags=stacking,reordering,invert,reverse
plugins=com.npcstackreorderer.NpcStackReordererPlugin
